### ISSUE TITLE
Boucle infini

### ISSUE THREAD

**Issue by Quentinix** [thibaut-decherit/symfony-user-manager#30]
https://github.com/thibaut-decherit/symfony-user-manager/blob/6db996d1b15b1c8b4336bdd018e7c938c1c851b7/src/AppBundle/Command/RemoveUnactivatedAccountsCommand.php#L50

Il me semble que $users n'est pas vide si la boucle foreach est finit.

**Comment by thibaut-decherit** [comment]
Non, mais à la prochaine itération `findUnactivatedAccountsOlderThan()` renverra le prochain "lot" d'users à supprimer, ou un array vide si plus aucun user ne correspond aux critères de recherche.

Or, si l'array est vide, on rentrera alors dans la condition `if (empty($users))`, ce qui met fin à la boucle.

**Comment by Quentinix** [comment]
Ha d'accord, je comprend.
C'est vrais que j'ai plus mes connaissances sur Symfony. ;)
